<?php 
@define ('_nhapmabaomat','Nhập mã bảo mật');
@define ('_sendmailus','Gửi thư cho chúng tôi');
@define ('_resultsearch','Kết quả tìm kiếm');
@define ('_resultfound','Kết quả được tìm thấy!');
@define ('_have','Có');
@define ('_search','Tìm kiếm');
@define ('_gioithieu','Giới thiệu ');
@define ('_spdangcapnhat','Sản phẩm đang cập nhật ..... ');
@define ('_thongtinsp','Thông tin sản phẩm');
@define ('_lienhemuahang','Liên hệ ');
@define ('_dangky','Đăng ký');
@define ('_phanloai','Phân loại');
@define ('_xuatxu','Xuất xứ');
@define ('_xemchitiet','Xem chi tiết');
@define ('_baivietdangcapnhat','Bài viết đang cập nhật');
@define ('_mostviewed','Bài viết xem nhiều nhất');
@define ('_viewonmap','Xem trên bản đồ');
@define ('_dangkynhantin','Đăng ký nhận tin');
@define ('_emairegisty','Email đăng ký');
@define ('_gui','Gửi');
@define ('_phonevalid','Số điện thoại không được để trống');
@define ('_emailvalid','Email không được để trống');
@define ('_namevalid','Họ tên không được để trống');
@define ('_guiyeucauhotro','Gửi yêu cầu hỗ trợ');
@define ('_phonenumber','Số điện thoại');
@define ('_hovaten','Họ và tên');
@define ('_supportcenter','Trung tâm hỗ trợ');
@define ('_cuaagrimatco','của AGRIMATCO');
@define ('_doitac','Đối tác');
@define ('_testcenter','Trung tâm khảo nghiệm');
@define ('_aroundworld','Trên toàn thế giới');
@define ('_cuaagrimatcovn','của AGRIMATCO Việt Nam');
@define ('_tatcasp','Tất cả sản phẩm');
@define ('_ve','Về');
@define ('_vethoitiet','Về thời tiết');
@define ('_dubao','Dự báo');
@define ('_timhieuthem','Tìm hiểu thêm');
@define ('_agrimatcovn','AGRIMATCO Việt Nam');
@define ('_bantin','Bản tin');
@define ('_cungcap','Cung cấp ');
@define ('_agrimatco','AGRIMATCO');
@define ('_hoatdong','Hoạt động');
@define ('_guithongtin','Gửi thông tin');
@define ('_thongtinlienhe','Thông tin liên hệ');
@define ('_thoat','Thoát');
@define ('_hoantat','Hoàn tất');
@define ('_thutu','Thứ tự');
@define ('_thietlaphethong','Thiết lập hệ thống');
@define ('_cauhinhwebsite','Cấu hình website');
@define ('_linkmessage','Link message');
@define ('_hethongcuahang','Hệ thống cửa hàng');
@define ('_toadoweb','Tọa độ web');
@define ('_laymanhung','Lấy mã nhúng');
@define ('_nhungiframe','Nhúng Iframe Map');
@define ('_codebody','Code Body');
@define ('_codehead','Code Annalytics');
@define ('_soluongphantrang','Số SP phân trang');
@define ('_thuoctinhcauhinh','Thuộc tính cấu hình');
@define ('_website','Website');
@define ('_sozalo','Số zalo');
@define ('_dienthoai','Điện thoại');
@define ('_hotline','Hotline');
@define ('_email','Email');
@define ('_diachi','Địa chỉ');
@define ('_thongtinchung','Thông tin chung');
@define ('_location','Chỉ đường');
@define ('_call','Gọi ngay');
@define ('_cauhinhchung','Cấu hình chung');
@define ('_productrelated','Sản phẩm liên quan');
@define ('_noidungchitiet','Nội dunng chi tiết');
@define ('_giagoc','Giá gốc');
@define ('_giaban','Giá bán');
@define ('_outstock','Hết hàng');
@define ('_stock','Còn hàng');
@define ('_tinhtrang','Tình trạng');
@define ('_luotxem','Lượt xem');
@define ('_danhmuc','Danh mục');
@define ('_masp','Mã sản phẩm');
@define ('_home','Trang chủ');
@define ('_timework','Thời gian làm việc');
@define ('_connect_with_us','Kết nối với chúng tôi');
@define ('_map','Bản đồ ');
@define ('_chinhsach','Chính sách bán hàng');
@define ('_readmore','Đọc thêm');
@define ('_sua','Sửa');
@define ('_them','Thêm');
@define ('_danhmucsp','Danh mục sản phẩm');
@define ('_newproduct','Sản phẩm mới');
@define ('_logout','Đăng xuất');
@define ('_vaowebsite','Vào website');
@define ('_capnhatsitemap','Cập nhật site map');
@define ('_hientai','Hiện tại');
@define ('_kytu','Ký tự');
@define ('_noidung','Nội dung');
@define ('_noidungseo','Nội dung seo');
@define ('_mota','Mô tả');
@define ('_thuoctinh','Thuộc tính');
@define ('_account','Tài khoản');
@define ('_thongtin','Thông tin');
@define ('_tendanhmuc','Tên danh mục');
@define ('_viewmore','Xem thêm');
@define ('_sothutu','STT');
@define ('_anhien','Ẩn hiện');
@define ('_links','Link');
@define ('_tieude','Tiêu đề');
@define ('_uploadhinhanh','Upload hình ảnh');
@define ('_hinhanh','Hình ảnh');
@define ('_tatca','Tất cả');
@define ('_danhsach','Danh sách');
@define ('_tenhinh','Tên hình');
@define ('_stt','STT');
@define ('_nhaptukhoatimkiem','Nhập từ khoá tìm kiếm...');
@define ('_chooselang','Chọn ngôn ngữ');
@define ('_thaotac','Thao tác');
@define ('_tenbien','Tên biến');
@define ('_ngonngu','Ngôn ngữ');
@define ('_en','English');
@define ('_vi','Việt Nam');
@define ('_lienhe','Liên hệ');
@define ('_aboutus','Về chúng tôi ');
@define ('_thuvien_kythuat','Thư viện kỹ thuật');
@define ('_tintuc','Tin tức');
@define ('_dichvu','Dịch vụ');
@define ('_ungdung','Ứng dụng');
@define ('_sanpham','Sản phẩm');
?>