<?php 
@define ('_nhapmabaomat','Enter security code');
@define ('_sendmailus','Send mail for us');
@define ('_resultsearch','Result search');
@define ('_resultfound','Result found');
@define ('_have','Has');
@define ('_search','Search');
@define ('_gioithieu','About');
@define ('_spdangcapnhat','Product on updating');
@define ('_thongtinsp','Product Information');
@define ('_lienhemuahang','Contact ');
@define ('_dangky','Register');
@define ('_phanloai','Classify');
@define ('_xuatxu','Origin');
@define ('_xemchitiet','View detail');
@define ('_baivietdangcapnhat','Article on updating');
@define ('_mostviewed','Most viewed Article');
@define ('_viewonmap','View on map');
@define ('_dangkynhantin',' Sign up for');
@define ('_emairegisty','Email registration');
@define ('_gui','Send');
@define ('_phonevalid','Please fill phone');
@define ('_emailvalid','Please fill email');
@define ('_namevalid','Please fill fullname');
@define ('_guiyeucauhotro','Send support request');
@define ('_phonenumber','Phone number');
@define ('_hovaten','Fullname');
@define ('_supportcenter','Support center');
@define ('_cuaagrimatco','of AGRIMATCO');
@define ('_doitac','Partner');
@define ('_testcenter','Test center');
@define ('_aroundworld','Around the world');
@define ('_cuaagrimatcovn','of  AGRIMATCO Vietnam');
@define ('_tatcasp','All product');
@define ('_ve','About');
@define ('_vethoitiet','Weather');
@define ('_dubao','Forecast');
@define ('_timhieuthem','More information');
@define ('_agrimatcovn','Vietnam AGRIMATCO');
@define ('_bantin','News');
@define ('_cungcap','provided');
@define ('_agrimatco','AGRIMATCO');
@define ('_hoatdong','Activity');
@define ('_guithongtin','Send Information');
@define ('_thongtinlienhe','Contact Information');
@define ('_thoat','Exit');
@define ('_hoantat','Finish');
@define ('_thutu','No.');
@define ('_thietlaphethong','System set up');
@define ('_cauhinhwebsite','Website config');
@define ('_linkmessage','Link message');
@define ('_hethongcuahang','Store system');
@define ('_toadoweb','Web location');
@define ('_laymanhung','Get embed Iframe ');
@define ('_nhungiframe','Embed Iframe Map');
@define ('_codebody','Code Body');
@define ('_codehead','Code Annalytics');
@define ('_soluongphantrang','Product paging number');
@define ('_thuoctinhcauhinh','Config attribute');
@define ('_website','Website');
@define ('_sozalo','Zalo number');
@define ('_dienthoai','Phone');
@define ('_hotline','Hotline');
@define ('_email','Email');
@define ('_diachi','Address');
@define ('_thongtinchung','General information');
@define ('_location','Location');
@define ('_call','Call');
@define ('_cauhinhchung','Setting');
@define ('_productrelated','Related Product');
@define ('_noidungchitiet','Details');
@define ('_giagoc','Price');
@define ('_giaban','Sale Price');
@define ('_outstock','Out of stock');
@define ('_stock','Available');
@define ('_tinhtrang','Status');
@define ('_luotxem','View');
@define ('_danhmuc','Category');
@define ('_masp','Product Code');
@define ('_home','Home');
@define ('_timework','Working Time');
@define ('_connect_with_us','Connect with us');
@define ('_map','Map');
@define ('_chinhsach','Sales Policy');
@define ('_readmore','Read more');
@define ('_sua','Edit');
@define ('_them','Add');
@define ('_danhmucsp','Product Category');
@define ('_newproduct','New product');
@define ('_logout','Logout');
@define ('_vaowebsite','Enter website');
@define ('_capnhatsitemap','Update sitemap');
@define ('_hientai','Current');
@define ('_kytu','Char');
@define ('_noidung','Content');
@define ('_noidungseo','Seo content');
@define ('_mota','Description');
@define ('_thuoctinh','Attribute');
@define ('_account','Account');
@define ('_thongtin','Information');
@define ('_tendanhmuc','Category name');
@define ('_viewmore','View more');
@define ('_sothutu','STT');
@define ('_anhien',' Hide show');
@define ('_links','Link');
@define ('_tieude','Title');
@define ('_uploadhinhanh','Upload image');
@define ('_hinhanh','Image');
@define ('_tatca','All');
@define ('_danhsach','List');
@define ('_tenhinh','Image Name');
@define ('_stt','STT');
@define ('_nhaptukhoatimkiem','Enter keywords ...');
@define ('_chooselang','Choose language');
@define ('_thaotac','Control');
@define ('_tenbien','Variable name');
@define ('_ngonngu','Language');
@define ('_en','English');
@define ('_vi','Vietnamese');
@define ('_lienhe','Contact');
@define ('_aboutus','About Us');
@define ('_thuvien_kythuat','Technical Library');
@define ('_tintuc','News');
@define ('_dichvu','Service');
@define ('_ungdung','Application');
@define ('_sanpham','Product');
?>